spring.application.name=gestionImmobiliere

# Logging niveau DEBUG pour Spring Security et Web
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.cors=DEBUG
#logging.level.com.immobilier=DEBUG

# Afficher les détails des requêtes
#spring.mvc.log-request-details=true



# Production
#server.servlet.session.cookie.secure=true
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.same-site=strict
