spring.application.name=gestionImmobiliere

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/location_db
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
# 🔴 Important : ne pas créer/modifier les tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Formater joliment les requêtes (plus lisible)
spring.jpa.properties.hibernate.format_sql=true
# Afficher les valeurs des paramètres (pour le débogage)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#jwtSecretAccessKey=wvs1L1a|]boMdXW5PAqaa%?Gv3noZ[g9/ycBv:KMD}L
#jwtSecretRefreshKey=ur>dS_Qv6<u4m2[.9LwX$RK$$S#U^:7DBwr#VQm[5V[
jwtSecretAccessKey=19226e65bfe578284ccf7f6ce9ba127ed59c51958b0501934c612d4b3ad2c9b234f4125fb87672142e614985a100ef4e500ac7bb105e374091649c2923984049
jwtSecretRefreshKey=cd0b606372be46cb2188b67917fc3d2a982d61f12cfd218504e54b57ae02ceed1d232d77ffc419e7c941e71083c2710dbbb47f7013c9aced863c62c4097a8d8b
finger.secret.key=5010a16b8792d9035bda972f1f1fe2a9b5017daeef34c9da6539700f297b3880df5efae350617f8d58e8206fc97311ce42173302271ff6613b52dbeb5c575510
jwtAccesExpiration=900000
jwtRefreshExpiration=604800000

jwt.refresh.cookie.name=refresh_token

# Production
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict