spring.application.name=gestionImmobiliere

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/location_db
spring.datasource.username=postgres
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
# 🔴 Important : ne pas créer/modifier les tables
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
# Formater joliment les requêtes (plus lisible)
spring.jpa.properties.hibernate.format_sql=true
# Afficher les valeurs des paramètres (pour le débogage)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



jwt.secret.access=19226e65bfe578284ccf7f6ce9ba127ed59c51958b0501934c612d4b3ad2c9b234f4125fb87672142e614985a100ef4e500ac7bb105e374091649c2923984049
jwt.secret.refresh=cd0b606372be46cb2188b67917fc3d2a982d61f12cfd218504e54b57ae02ceed1d232d77ffc419e7c941e71083c2710dbbb47f7013c9aced863c62c4097a8d8b
finger.secret.key=5010a16b8792d9035bda972f1f1fe2a9b5017daeef34c9da6539700f297b3880df5efae350617f8d58e8206fc97311ce42173302271ff6613b52dbeb5c575510

jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# Configuration des cookies
jwt.cookie.access.name=access_token
jwt.cookie.refresh.name=refresh_token
jwt.cookie.secure=true
jwt.cookie.same-site=Strict
jwt.redis.secure=false

app.base-url=http://localhost:8080



# Production
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

#config email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ============================================================
# REDIS CONFIGURATION
# ============================================================

# Serveur Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.database=0

# Pool de connexions
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

# Timeout (millisecondes)
spring.data.redis.timeout=5000
spring.data.redis.lettuce.shutdown-timeout=2000